name: Build Mac App

on:
  push:
    branches:
      - main  # or 'master' if your branch is named master

jobs:
  build:
    runs-on: macos-latest  # This tells GitHub to use a Mac!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: Clean build artifacts
      run: |
        rm -rf build dist *.egg-info


    - name: Clean build artifacts again
      run: |
        rm -rf build dist *.egg-info

    - name: Remove backports.tarfile if present
      run: |
        rm -rf build/bdist.macosx-10.9-universal2/python3.10-standalone/app/collect/backports.tarfile*

    - name: Build the app
      run: |
        source venv/bin/activate
        python setup.py py2app --force

    - name: Upload built app
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: dist/*.app
